apps/adopcion/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from . import views
from apps.adopcion.views import index_adopcion, SolicitudList, SolicitudCreate, SolicitudUpdate, SolicitudDelete, DetailSolicitud, DetailPersona, \
    ListSolicitud, ListPersona, listadoPersona, listadoSolicitud

urlpatterns = [
    #path('admin/', admin.site.urls),
    #url(r'^index$', index_adopcion),
    url(r'^$', login_required(index_adopcion), name='index_adopcion'),
    url(r'^listar', login_required(SolicitudList.as_view()), name='solicitud_listar'),
    url(r'^nueva$', login_required(SolicitudCreate.as_view()), name='solicitud_crear'),
    #url(r'^nueva$', login_required(views.solicitud), name='solicitud_crear'),
    url(r'^editar/(?P<pk>\d+)$', login_required(SolicitudUpdate.as_view()), name='solicitud_editar'),
    url(r'^eliminar/(?P<pk>\d+)$', login_required(SolicitudDelete.as_view()), name='solicitud_eliminar'),

    #API
    url(r'^listadoPersona$', login_required(listadoPersona), name='listado_persona'),
    url(r'^listadoSolicitud$', login_required(listadoSolicitud), name='listado_solicitud'),

    #api en uso
    url(r'^api/solicitudes/$', ListSolicitud.as_view(), name='solicitud_api'), #GET, POST
    url(r'^api/solicitud/(?P<pk>\d+)$', DetailSolicitud.as_view(), name='solicitud_detail'), #PUT, DELETE

    url(r'^api/personas/$', ListPersona.as_view(), name='personas_api'), #GET, POST
    url(r'^api/persona/(?P<pk>\d+)$', DetailPersona.as_view(), name='persona_detail'), #PUT, DELETE

    #api en uso
    #url(r'^api/solicitudes/$', ListSolicitud.as_view(), name='solicitud_api'),
    #url(r'^api/personas/$', ListPersona.as_view(), name='personas_api'),
]

refugio/urls.py
from django.conf.urls import url, include
from django.contrib.auth import urls
from django.contrib import admin
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView, logout_then_login, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView, LogoutView
#password_reset, password_reset_done, password_reset_confirm, password_reset_complete


urlpatterns = [
    path('admin/', admin.site.urls),
    #APIs
    path('', include('apps.usuario.urls')),
    path('', include('apps.mascota.urls')), #incluye mascotas y vacunas
    path('', include('apps.adopcion.urls')),
    path('mascota/', include ('apps.mascota.urls'), name='mascota'),
    path('adopcion/', include ('apps.adopcion.urls'), name='adopcion'),
    path('solicitud/', include ('apps.adopcion.urls'), name='solicitud'),
    path('usuario/', include ('apps.usuario.urls'), name='usuario'),
    #url(r'^registrar$', RegistroUsuario.as_view(), name='registrar'),
    #path('usuario/', include('django.contrib.auth.urls')), #TODAS LAS URL
    #path('logout/', LogoutView.as_view(template_name='usuario/login.html'), name='logout'),
    path('logout/', logout_then_login, name='logout'),
    path('accounts/login/', LoginView.as_view(template_name='usuario/login.html'), name='login'),
    path('reset/password_reset', PasswordResetView.as_view(template_name='registration/password_reset_form.html'), name='password_reset'), #, 'email_template_name':'registration/password_reset_email.html'
    path('reset/password_reset_done', PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done', PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    path('api-auth/', include('rest_framework.urls')),

    path('bootstrap/', TemplateView.as_view(template_name='bootstrap/example.html')),
]

urlpatterns += staticfiles_urlpatterns()

#path('', login, {'template_name':'index.html'}, name='login'),
#path('password_reset/', auth_views.PasswordResetView.as_view(success_url=reverse_lazy('users:password_reset_done')), name='password_reset'),



    #path('logout/', logout_then_login, name='logout'),
    #path('accounts/login/', LoginView.as_view(template_name='usuario/index.html'), name='login'),
    #path('reset/password_reset', PasswordResetView.as_view(template_name='registration/password_reset_form.html'), name='password_reset'), #, 'email_template_name':'registration/password_reset_email.html'
    #path('reset/password_reset_done', PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    #path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    #path('reset/done', PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),

apps/adopcion/models.py
from django.db import models
from django.conf import settings
#from apps.usuario.models import User
from apps.usuario.models import get_request_user
from apps.usuario.views import current_user
#from apps.adopcion.views import *
from django.contrib.auth.models import User
from django.contrib.auth.signals import user_logged_in

# Create your models here.

class Persona(models.Model):
    #folio = models.CharField(max_length=10, primary_key=True)
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=70)
    edad = models.IntegerField()
    telefono = models.CharField(max_length=12)
    email = models.EmailField()
    domicilio = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        #esto es para que retorne nombre y apellido en lugar del objeto
        return '{} {}'.format(self.nombre, self.apellido)

class Solicitud(models.Model):

    def user_logged_in_handler(self, sender, request, user, **kwargs):
        User.objects.get_or_create(
        user = user,
        session_id = request.session.session_key
    )
    #user_logged_in.connect(user_logged_in_handler)

    usuario = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE) #db_column='usuario_id', default=get_request_user(), default=id(3) #default=User.objects.get(pk=2)
    #usuario  = models.ForeignKey(User, related_name='username', on_delete=models.CASCADE) #default=user_logged_in.connect(user_logged_in_handler), 
    #usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,)
    #user_logged_in.connect(user_logged_in_handler)
    #usuario = models.TextField()
    numero_mascotas = models.IntegerField()
    razones = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    #user = models.OneToOneField(User) #relacion uno a uno de solicitud con usuario, luego de esto hay que hacer makemigrations con la opc 1, luego migrate

    
    def __str__(self):
        #esto es para que retorne el nombre completo de la persona y el id de la solicitud en lugar del objeto
        if ('{}'.format(self.usuario) == 'None'):
            return '{}'.format(self.id) + ' de ' + 'ANONIMO'
        else:
            return '{}'.format(self.id) + ' de ' + '{}'.format(self.usuario)
    
    #def __init__(self, request, *args, **kwargs):
    #    super(Solicitud, self).__init__(*args, **kwargs)
    #    self.fields['usuario_id'].queryset =  User.objects.filter(user=request.user)

    #def get_user(self):
        #return '{}'.format(self.id)
        #ATRIBUTO QUE RELACIONA Solicitud/Usuario
        #user = User.get_username

    #def __str__(self):
    #    return self.usuario.username

    #def get_request_user(self, request):
        # or any complex query result to set default value in ForeignKey
        #return request.user.id

apps/mascota/models.py
from django.db import models

from apps.adopcion.models import Persona, Solicitud, User
from django.contrib.auth.models import User

# Create your models here.

class Vacuna(models.Model):
    nombre = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        #esto es para que retorne el nombre de la vacuna en administracion (no el objeto)
        return '{}'.format(self.nombre)

class Mascota(models.Model):
    #folio = models.CharField(max_length=10, primary_key=True)
    nombre = models.CharField(max_length=50)
    sexo = models.CharField(max_length=10)
    edad_aproximada = models.IntegerField()
    fecha_rescate = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    #ATRIBUTO QUE RELACIONA Mascota/Persona
    usuario = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)

    #ATRIBUTO QUE RELACIONA LOS DOS MODELOS (Mascota/Vacuna)
    vacuna = models.ManyToManyField(Vacuna, blank=True)

    def __str__(self):
        #esto es para que retorne el nombre de la mascota en administracion (no el objeto)
        return '{}'.format(self.nombre)

codigo de prueba/adopcion/models.py
from django.db import models
from apps.usuario.models import User
from django.contrib.auth.models import User

# Create your models here.

class Persona(models.Model):
    #folio = models.CharField(max_length=10, primary_key=True)
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=70)
    edad = models.IntegerField()
    telefono = models.CharField(max_length=12)
    email = models.EmailField()
    domicilio = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        #esto es para que retorne nombre y apellido en lugar del objeto
        return '{} {}'.format(self.nombre, self.apellido)

class Solicitud(models.Model):
    #ATRIBUTO QUE RELACIONA Solicitud/Persona
    usuario = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)

    numero_mascotas = models.IntegerField()
    razones = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    #user = models.OneToOneField(User) #relacion uno a uno de solicitud con usuario, luego de esto hay que hacer makemigrations con la opc 1, luego migrate
    
    #def __str__(self):
    #    return self.usuario.username

    
    def __str__(self):
        #esto es para que retorne el nombre completo de la persona y el id de la solicitud en lugar del objeto
        if ('{}'.format(self.usuario) == 'None'):
            return '{}'.format(self.id) + ' de ' + 'ANONIMO'
        else:
            return '{}'.format(self.id) + ' de ' + '{}'.format(self.usuario)
    

apps/adopcion/forms.py
from django import forms
from django.forms import ModelForm
from apps.adopcion.models import Persona, Solicitud
from apps.usuario.models import User
from django.contrib.auth.models import User

class PersonaForm(forms.ModelForm):

    class Meta:
        model = Persona

        fields = [
            'nombre',
            'apellido',
            'edad',
            'telefono',
            'email',
            'domicilio',
        ]
        labels = {
            'nombre': 'Nombre',
            'apellido': 'Apellido',
            'edad': 'Edad',
            'telefono': 'Teléfono',
            'email': 'Correo Electrónico',
            'domicilio': 'Domicilio',
        }
        widgets = {
            'nombre': forms.TextInput(attrs={'class':'form-control'}),
            'apellido': forms.TextInput(attrs={'class':'form-control'}),
            'edad': forms.TextInput(attrs={'class':'form-control'}),
            'telefono': forms.TextInput(attrs={'class':'form-control'}),
            'email': forms.TextInput(attrs={'class':'form-control'}),
            'domicilio': forms.Textarea(attrs={'class':'form-control'}),
        }

class SolicitudForm(forms.ModelForm):

    class Meta:

        model = Solicitud
        #modelUser = User
        #usuario = forms.ModelChoiceField(queryset=User.objects.all())
        
        fields = [
            'usuario',
            'numero_mascotas',
            'razones',
        ]
        labels = {
            'usuario': 'Usuario',
            'numero_mascotas': 'Numero de mascotas',
            'razones': 'Razones para adoptar',
        }
        widgets = {
            #'usuario': forms.TextInput(attrs={'class':'form-control'}),
            'usuario':forms.Select(attrs={'class':'form-control'}), #tiene que quedar fijo el usuario logueado
            'numero_mascotas': forms.NumberInput(attrs={'class':'form-control', 'min': 1, 'max': 5}),
            'razones':forms.Textarea(attrs={'class':'form-control'}),
        }

        #def __init__(self, request, *args, **kwargs):
        #    super().__init__(*args, **kwargs)
        #    self.fields['usuario'].queryset = User.objects.filter(user=request.user)

        """
        def __init__(self, *args, **kwargs):
            self.created_by = kwargs['initial']['created_by']
            super(SolicitudForm, self).__init__(*args, **kwargs)

        def save(self, commit=True):
            obj = super(SolicitudForm, self).save(False)
            obj.created_by = self.created_by
            commit and obj.save()
            return obj
        """



class SolicitudForm2(forms.Form):
    usuario = forms.ModelChoiceField(queryset=User.objects.all())
    #usuario = forms.ChoiceField()
    numero_mascotas = forms.IntegerField(required=True, min_value=1, max_value=5)
    razones = forms.CharField(required=True)

templates/adopcion/delete.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">

    {% csrf_token %}
    <h3>¿Desea eliminar la solicitud de {{ object.persona.nombre }} {{ object.persona.apellido }}?</h3>
    
    <button class="btn btn-danger" type="submit">Si, eliminar</button>
    <a class="btn btn-default" href="{% url 'solicitud_listar' %}">Cancelar</a>

</form>

{% endblock %}

templates/adopcion/form.html
{% extends 'base/base.html' %}

{% block content %}
<!--
<div class="row">
    <div class="col-md-8 col-md-offset-4">
        <a style="float:right; color:blue;" href="{{request.META.HTTP_REFERER}}" class="btn">Volver</a>
    </div>
</div>
-->
<div class="row">
    <div class="col-md-8 col-md-offset-0">
        <h1>Complete su solicitud</h1>
    </div>
</div>

<form method="post">

    {% csrf_token %}
    
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label>Persona</label>
                {% if object_list %}
                {% for solicitud in object_list %}
                <a>{{ form.nombre.name }}</a>
                {% endfor %}
        
                {% else %}
                <h1> No hay registros de solicitudes</h1>
                {% endif %}
                <select class="form-control" type="text" name="nombre" value='{{ persona.nombre }}'>{{ solicitud.persona.nombre }}</select>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label for="{{ form.nombre.name }}">{{ form.nombre.label }}</label>
                {{ solicitud.nombre }}
            </div>
        </div>
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label for="{{ form.apellido.name }}">{{ persona.apellido.label }}</label>
                {{ form.persona.apellido.label }}
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label>Cantidad de mascotas</label>
                <input class="form-control" type="number" min="1" max="5" name="numero_mascotas" value='{{ persona.numero_mascotas }}'>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label>Razones de adopción</label>
                <textarea class="form-control" rows="3" name="razones" value='{{ persona.razones }}'></textarea>
            </div>
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <button class="btn btn-primary" type="submit">Guardar</button>
            </div>
        </div>
    </div>

</form>

{% endblock %}

<!--
    
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label for="{{ form.numero_mascotas.name }}">{{ form.numero_mascotas.label }}</label>
                {{ form.numero_mascotas }}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label for="{{ form.razones.name }}">{{ form.razones.label }}</label>
                {{ form.razones }}
            </div>
        </div>
    </div>

-->

templates/adopcion/form2.html
{% extends 'base/base.html' %}

{% block content %}
<!--
<div class="row">
    <div class="col-md-8 col-md-offset-4">
        <a style="float:right; color:blue;" href="{{request.META.HTTP_REFERER}}" class="btn">Volver</a>
    </div>
</div>
-->
<div class="row">
    <div class="col-md-8 col-md-offset-0">
        <h1>Complete su solicitud</h1>
    </div>
</div>
<!--
<form method="post">
    {% csrf_token %}
    {{ form }}
    <button class="btn btn-primary" type="submit">Guardar</button>
</form>
-->

<form method="post">
{% csrf_token %}

    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label>Adoptante</label>
                <text class="form-control" disabled>{{ request.user }}</text>
                <select class="form-control" name="usuario" hidden=True value='{{ solicitud.usuario }}'>
                    <option>{{ request.user.id }}</option>
                </select>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label>Cantidad de mascotas</label>
                <input class="form-control" type="number" min="1" max="5" name="numero_mascotas" value='{{ solicitud.numero_mascotas }}'>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label>Razones de adopción</label>
                <input class="form-control" rows="3" name="razones" value='{{ solicitud.razones }}'>
            </div>
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <button class="btn btn-primary" type="submit">Guardar</button>
            </div>
        </div>
    </div>
</form>

{% endblock %}

<!--

<form method="post">
{% csrf_token %}
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label>Adoptante</label>
    
                <a 
                <input class="form-control" name="usuario" value='{{ solicitud.usuario }}'>{{ request.user.username }}</a>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label>Cantidad de mascotas</label>
                <input class="form-control" type="number" min="1" max="5" name="numero_mascotas" value='{{ solicitud.numero_mascotas }}'>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label>Razones de adopción</label>
                <textarea class="form-control" rows="3" name="razones" value='{{ solicitud.razones }}'></textarea>
            </div>
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <button class="btn btn-primary" type="submit">Guardar</button>
            </div>
        </div>
    </div>
</form>


-->

<!-- <a class="form-control" name="usuario" value='{{ solicitud.usuario }}'>{{ user.get_username }}</a> -->

<!--
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label>Adoptante</label>
                <select class="form-control" name="usuario" value='{{ solicitud.usuario }}'>
                    {% if object_list %}
                    {% for usuario in object_list %}
                        {{ usuario.username }}
                    {% endfor %}
                    {% endif %}
                </select> 
            </div>
        </div>
    </div>
-->
<!-- {{ request.user.id }} disabled=True -->

templates/adopcion/form_doble.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">

    {% csrf_token %}

    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label for="{{ form2.nombre.name }}">{{ form2.nombre.label }}</label>
                {{ form2.nombre }}
            </div>
        </div>
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label for="{{ form2.apellido.name }}">{{ form2.apellido.label }}</label>
                {{ form2.apellido }}
            </div>
        </div>
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label for="{{ form2.email.name }}">{{ form2.email.label }}</label>
                {{ form2.email }}
            </div>
        </div>   
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label for="{{ form2.telefono.name }}">{{ form2.telefono.label }}</label>
                {{ form2.telefono }}
            </div>
        </div>     
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label for="{{ form2.domicilio.name }}">{{ form2.domicilio.label }}</label>
                {{ form2.domicilio }}
            </div>
        </div>
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label for="{{ form1.numero_mascotas.name }}">{{ form1.numero_mascotas.label }}</label>
                {{ form1.numero_mascotas }}
            </div>
        </div>
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label for="{{ form1.razones.name }}">{{ form1.razones.label }}</label>
                {{ form1.razones }}
            </div>
        </div>
    </div>
    <div class="col-md-8 col-md-offset-2">
        <div class="form-group">
            <button class="btn btn-primary" type="submit">Guardar</button>
        </div>
    </div>
</form>

{% endblock %}

templates/adopcion/form_old.html
{% extends 'base/base.html' %}

{% block content %}
<!--
<div class="row">
    <div class="col-md-8 col-md-offset-4">
        <a style="float:right; color:blue;" href="{{request.META.HTTP_REFERER}}" class="btn">Volver</a>
    </div>
</div>
-->
<div class="row">
    <div class="col-md-8 col-md-offset-0">
        <h1>Complete su solicitud</h1>
    </div>
</div>

<form method="post">

    {% csrf_token %}
    <p>
    {{ form.as_p }}
    <button class="btn btn-primary" type="submit">Guardar</button>
    </p>
</form>

{% endblock %}

<!-- {{ form1.nombre }} 
    {{ form2.as_p }} -->

    <!--
    <form method="post">

        <p>
        </p><p><label for="id_nombre">Nombre:</label> <input type="text" name="nombre" class="form-control" maxlength="50" required="" id="id_nombre"></p>
    <p><label for="id_sexo">Sexo:</label> <input type="text" name="sexo" class="form-control" maxlength="10" required="" id="id_sexo"></p>
    <p><label for="id_edad_aproximada">Edad aproximada:</label> <input type="text" name="edad_aproximada" class="form-control" required="" id="id_edad_aproximada"></p>
    <p><label for="id_fecha_rescate">Fecha de rescate:</label> <input type="text" name="fecha_rescate" class="form-control" required="" id="id_fecha_rescate"></p>
    <p><label for="id_usuario">Adoptante:</label> <select name="usuario" class="form-control" id="id_usuario">
      <option value="" selected="">---------</option>
    
      <option value="1">admin</option>
    
      <option value="2">ricardoalvarez</option>
    
      <option value="3">bvitucci</option>
    
    </select></p>
    <p><label>Vacunas:</label> </p><ul id="id_vacuna">
        <li><label for="id_vacuna_0"><input type="checkbox" name="vacuna" value="1" id="id_vacuna_0">
     canina1</label>
    
    </li>
        <li><label for="id_vacuna_1"><input type="checkbox" name="vacuna" value="2" id="id_vacuna_1">
     felina1</label>
    
    </li>
    </ul><p></p>
        <button class="btn btn-primary" type="submit">Guardar</button>
        <p></p>
    </form>

        <p><label for="id_numero_mascotas">Cantidad de mascotas:</label> <input class="form-control" type="number" min="1" max="5" name="numero_mascotas" value="{{ solicitud.numero_mascotas }}"></p>
    <p><label for="id_razones">Razones:</label> <textarea class="form-control" rows="3" name="razones" value="{{ solicitud.razones }}"></textarea> </p>
    <p><label for="id_usuario">Adoptante:</label> <input class="form-control" type="text" name="usuario" value="{{ form.usuario }}"></p>
    <p><label for="id_usuario">Adoptante:</label> <input type="text" name="usuario" class="form-control" id="id_usuario" value="{{ user.first_name }} {{ user.last_name }}" disabled></p>
    
-->

templates/adopcion/list.html
{% extends 'base/base.html' %}

{% block content %}
<!--
<div class="row">
    <div class="col-md-8 col-md-offset-4">
        <a style="float:right; color:blue;" href="{{request.META.HTTP_REFERER}}" class="btn">Volver</a>
    </div>
</div>
-->
<div class="row">
    <div class="col-md-8 col-md-offset-0">
        <h1>Solicitudes</h1>
    </div>
</div>

<table class="table table-bordered">
    <thead>
        <tr>
            <td>Nro. Solicitud</td>
            <td>Adoptante</td>
            <td>Nro. Mascotas</td>
            <td>Razones</td>
            <td>Acciones</td>
        </tr>
    </thead>
    <tbody>
        {% if object_list %}
        {% for solicitud in object_list %}
        <tr>
            <td>{{ solicitud.id }}</td>
            <td>{{ solicitud.usuario.first_name }} {{ solicitud.usuario.last_name }}</td>
            <td>{{ solicitud.numero_mascotas }}</td>
            <td>{{ solicitud.razones }}</td>
            <td>
                <a class="btn btn-primary" href="{% url 'solicitud_editar' solicitud.id %}">Editar</a>
                <a class="btn btn-danger" href="{% url 'solicitud_eliminar' solicitud.id %}">Eliminar</a>
            </td>
        </tr>
        {% endfor %}

        {% else %}
        <h1> No hay registros de solicitudes</h1>
        {% endif %}

    </tbody>
</table>

<ul class="pager">
    <li>
        {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}">Previa</a>
        {% endif %}
    </li>
    <li>
        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">Siguiente</a>
        {% endif %}
    </li>
</ul>

{% endblock %}


<!-- <td>{{ solicitud.persona.nombre }} {{ solicitud.persona.apellido }}</td> -->